services:
  convert-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - GOOGLE_USER_EMAIL=leorosso@reconectaoficial.com.br
      # Configurações de timeout para Node.js
      - NODE_OPTIONS=--max-old-space-size=4096
      # Transkriptor API Token
      - ACCESS_TOKEN_TRANSKRIPTOR=d1278f27349850804ad562232854e6cd18ced7dd842fc54c068fae9b653debcd1ddaa25ed451050543b99b2d017f26623a889405a02a9af2115d7447073dad63
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
    restart: unless-stopped
    # Configurações de timeout para Docker
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/video/status"]
      interval: 30s
      timeout: 30s  # Aumentado de 10s para 30s
      retries: 3
      start_period: 60s  # Aumentado de 40s para 60s 